import numpy as np
from pathlib import Path
import re
import networkx as nx
import pandas as pd


class DataManager:
    """
    Class intended to work with .g6 files treating .parquet file generated by `build_manifest.py`
    with the following head:
    | sample_id | source_file | local_idx | global_idx | graph6_rep | num_nodes | num_edges | planar |
    """

    def __init__(self, parquet_path: str, data_dir: str, seed=None):
        self.paruet_path = parquet_path
        self.data_ditr = data_dir
        self.manifest = None
        self.seed = seed
        self.rng = np.random.default_rng(seed) if seed is not None else None
        self.total_G = 11897979                         # would be nice to generalize down the road with geng

    def pull_shard(self, 
                   batch_id: int
                    )-> pd.DataFrame:
        """
        Pulls a shard based on a three digit ID
        Args:
            batch_id: Three digit ID for shard 000-111.
        Returns:
            Dataframe: a section of the parquet as a dataframe.
        """

        df = pd.read_parquet(self.paruet_path,
                             filters=[("batch_id", "==", batch_id)]
                             )
        # reset_index and drop=True since global info is still in the frame
        return df.sort_values(by="local_idx").reset_index(drop=True)

    def pull_slice(self, 
                   start_idx: int, 
                   end_index: int
                   ) -> pd.DataFrame:
        """
        Pulls a slice of a row from a start index, to end index.
        # impliment a logic to avoid out of bounds
        Args:
            start_idx:  non-negative integer indicating row to pull from
            end_idx: non-negative integer indicating row to pull from
        Returns:
            Dataframe: a section of the parquet as a dataframe
        """
        return pd.read_parquet(self.paruet_path)[start_idx:end_index]
    
    def sample_random_row(self):
        if self.rng is None:
            raise RuntimeError("Random operations require a seed")
        
        idx = self.rng.integers(0, len(self.manifest))
        return self.manifest.iloc[idx]
    
    def to_full_dataframe(self):
        return pd.read_parquet(self.paruet_path)

"""
class DataManager:
    def __init__(self, parquet_path, data_dir, seed=None):
        from pathlib import Path
        import numpy as np

        self.parquet_path = Path(parquet_path)
        self.data_dir = Path(data_dir)

        self.seed = seed
        self.rng = np.random.default_rng(seed) if seed is not None else None

    def sample_random_row(self):
        if self.rng is None:
            raise RuntimeError("Random operations require a seed")
        
        idx = self.rng.integers(0, len(self.manifest))
        return self.manifest.iloc[idx]

"""